### ISSUE TITLE
gpApply() fails to find source code when function is defined in python shell

### ISSUE THREAD

**Issue by lisakowen** [greenplum-db/GreenplumPython#33]
i am using the python3 shell to try out a greenplumpython that i built myself.  python version 3.6.8.

```
$ python3
>>> import pandas as pd
>>> import greenplumpython as gppy
>>> connection = gppy.GPConnection()
>>> conn = connection.connect( 'localhost', 6000, 'testdb', 'gpadmin', '')
>>> testdb_inst = gppy.GPDatabase(conn)
>>> dfwrap_table1 = testdb_inst.get_table( 'table1', 'public')
>>> otbl_cols = list()
>>> otuple = ('c1', 'int')
>>> otbl_cols.append(otuple)
>>> otbl_meta = gppy.GPTableMetadata(None, otbl_cols, None)
>>> # apply function
... def input_py_func(row_element, extra_args):
...     return row_element + extra_args
... 
>>> df = gppy.gpApply(dfwrap_table1, input_py_func, testdb_inst, otbl_meta, 'plc_python_shared')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gpadmin/GreenplumPython/greenplumpython/core/gpapply.py", line 39, in gpApply
    s = inspect.getsource(py_func)
  File "/usr/lib64/python3.6/inspect.py", line 973, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/lib64/python3.6/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib64/python3.6/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

this may be related:  https://stackoverflow.com/questions/57035364/inspect-getsourcelinesobject-shows-oserror-if-run-from-python-shell-but-gives

should gpApply() work when the function is defined inline in the shell work?  or do i need to define the function in a script?

**Comment by beeender** [comment]
GreenplumPython has been rewritten, this should not be valid anymore. Close.

**Comment by beeender** [comment]
#139 fixed the similar issue in new GreenplumPython
